/* eslint-disable no-multi-assign */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import React, { useRef } from "react";
import useRefs from "react-use-refs";

export default function PrinterHead(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/printerhead1.gltf");

  const [redLiquid, blueLiquid] = useRefs();

  materials.ClearPlastic.opacity =
    materials.BlueLiquid.opacity =
    materials.RedLiquid.opacity =
      0.2;
  materials.ClearPlastic.transparent =
    materials.BlueLiquid.opacity =
    materials.RedLiquid.opacity =
      true;

  useFrame(() => {
    redLiquid.current.rotateY(0.05);
    blueLiquid.current.rotateY(0.05);
    // redLiquid.current.rotation.y += 0.05;
    // blueLiquid.current.rotation.y += 0.05;
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={[1, 1, 0.83]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_1.geometry}
          material={materials.Metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_2.geometry}
          material={materials.GoldMetal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_3.geometry}
          material={materials.BlackMetal}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube001.material}
        position={[0.48, 0.21, 0.65]}
        scale={[1, 1, 0.8]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={nodes.Cube002.material}
        position={[0.48, 0.21, -0.63]}
        scale={[1, 1, 0.8]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={nodes.Cylinder.material}
        position={[0.59, 0.15, 0.29]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.19, -0.05, 0.19]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={nodes.Cylinder001.material}
        position={[0.59, 0.15, -0.27]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.19, -0.05, 0.19]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={nodes.Cylinder003.material}
        position={[0.62, 2.32, 1.09]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.19, -0.03, 0.19]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={nodes.Cylinder002.material}
        position={[0.62, 2.32, -1.08]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.19, -0.03, 0.19]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder004.geometry}
        material={nodes.Cylinder004.material}
        position={[0.58, 2.31, -1.08]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.22, 0.14, 0.22]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder005.geometry}
        material={nodes.Cylinder005.material}
        position={[0.58, 2.31, 1.09]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.22, 0.14, 0.22]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tip.geometry}
        material={nodes.Tip.material}
        position={[0, -0.03, 0]}
        scale={[0.25, 2.3, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder007.geometry}
        material={nodes.Cylinder007.material}
        position={[0, -0.03, 0]}
        scale={[0.25, 2.3, 0.25]}
      />
      <mesh
        ref={redLiquid}
        geometry={nodes.SpiralRed.geometry}
        material={materials.RedLiquid}
        position={[0, -1.74, 0]}
        scale={[0.9, 1, 0.9]}
      />
      <mesh
        ref={blueLiquid}
        geometry={nodes.SpiralBlue.geometry}
        material={materials.BlueLiquid}
        position={[0, -1.74, 0]}
        rotation={[-Math.PI, 0.36, -Math.PI]}
        scale={[0.9, 1, 0.9]}
      />
    </group>
  );
}

useGLTF.preload("/printerhead1.gltf");
